#!/bin/sh

# If you use pywal, you need to restore the scheme here
# (cat ~/.cache/wal/sequences &)

#export NNN_BMS="D:~/Downloads;v:~/Videos"
#export NNN_CONTEXT_COLORS="5236"
export NNN_USE_EDITOR=1
export NNN_TRASH=1
export NNN_PLUG='o:fzy-open;i:sxiv'
export NNN_OPENER=mimeopen
alias nsel="cat ${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection | tr '\0' '\n'"

# Unmask ^Q (if required, see `stty -a`) to Quit nnn
stty start undef
stty stop undef

# Start nnn with your preferred options
nnn -s "$@"
