#!/bin/sh


if [[ $# -eq 1 ]]
    for i in {1..4}; do scp $1 admin@192.168.56.10$i:; done
elif [[ $# -eq 4 ]]
then
    for i in $(seq $4); do
        "scp $1 admin@$2.$(($3+$i-1)):"
        echo $#
    done
else
    echo "
    This command requires four arguments:
        file
        first three octets (e.g. 192.168.77)
        last octet
        range
    example:
        scpall myFile 192.168.77 31 4"
fi

